<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Clinical Note #{{ $note->id }}: {{ $note->participant->mrn }}</title>
    <style>
        body { font-family: 'DejaVu Sans', Helvetica, sans-serif; font-size: 11px; color: #111; }
        h1 { font-size: 16px; margin: 0 0 10px 0; }
        h2 { font-size: 12px; margin: 12px 0 4px 0; text-transform: uppercase; border-bottom: 1px solid #888; padding-bottom: 2px; }
        .meta { font-size: 10px; color: #333; margin-bottom: 10px; }
        .body { white-space: pre-wrap; font-size: 11px; }
        .footer { margin-top: 20px; border-top: 1px solid #888; padding-top: 6px; font-size: 9px; color: #444; }
    </style>
</head>
<body>
    <h1>{{ ucfirst($note->note_type) }} Note</h1>
    <div class="meta">
        <strong>Participant:</strong> {{ $note->participant->last_name }}, {{ $note->participant->first_name }}
        &nbsp; MRN {{ $note->participant->mrn }}
        &nbsp; DOB {{ $note->participant->dob?->format('m/d/Y') }}<br>
        <strong>Visit:</strong> {{ $note->visit_date?->toDateString() }} · {{ $note->visit_type ?? '-' }}<br>
        <strong>Author:</strong> {{ $note->author?->first_name }} {{ $note->author?->last_name }}
        @if ($note->author?->department) ({{ $note->author->department }}) @endif<br>
        <strong>Status:</strong> {{ strtoupper($note->status) }}
        @if ($note->signed_at) · signed {{ $note->signed_at->toDateTimeString() }} by {{ $note->signedBy?->first_name }} {{ $note->signedBy?->last_name }} @endif
    </div>

    @if ($note->subjective)
        <h2>Subjective</h2>
        <div class="body">{{ $note->subjective }}</div>
    @endif
    @if ($note->objective)
        <h2>Objective</h2>
        <div class="body">{{ $note->objective }}</div>
    @endif
    @if ($note->assessment)
        <h2>Assessment</h2>
        <div class="body">{{ $note->assessment }}</div>
    @endif
    @if ($note->plan)
        <h2>Plan</h2>
        <div class="body">{{ $note->plan }}</div>
    @endif

    @if ($note->content)
        <h2>Content</h2>
        <div class="body">{{ is_array($note->content) ? json_encode($note->content, JSON_PRETTY_PRINT) : $note->content }}</div>
    @endif

    <div class="footer">
        Generated by NostosEMR · note #{{ $note->id }} · {{ now()->toDateTimeString() }} UTC
    </div>
</body>
</html>
