<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Signed Consent: {{ $consent->typeLabel() }}: {{ $participant->mrn }}</title>
    <style>
        body { font-family: 'DejaVu Sans', Helvetica, sans-serif; font-size: 11px; color: #111; }
        h1 { font-size: 16px; margin: 0 0 12px 0; }
        h2 { font-size: 12px; margin: 16px 0 6px 0; text-transform: uppercase; border-bottom: 1px solid #888; padding-bottom: 2px; }
        .meta-table { width: 100%; border-collapse: collapse; font-size: 10px; }
        .meta-table td { padding: 3px 6px; border-bottom: 1px solid #ddd; vertical-align: top; }
        .meta-table td:first-child { width: 35%; font-weight: bold; color: #444; }
        .signature-box { margin: 16px 0; padding: 10px; border: 1px solid #333; }
        .signature-box img { max-width: 360px; max-height: 120px; display: block; }
        .audit-stamp { margin-top: 20px; padding: 10px; background: #f4f4f4; border: 1px solid #bbb; font-size: 9px; color: #333; }
        .audit-stamp strong { color: #000; }
        .disclaimer { margin-top: 18px; font-size: 9px; color: #555; font-style: italic; }
    </style>
</head>
<body>
    <h1>{{ $consent->typeLabel() }}: Signed Acknowledgment</h1>

    <h2>Participant</h2>
    <table class="meta-table">
        <tr><td>Name</td><td>{{ $participant->last_name }}, {{ $participant->first_name }}</td></tr>
        <tr><td>MRN</td><td>{{ $participant->mrn }}</td></tr>
        <tr><td>Date of Birth</td><td>{{ $participant->dob?->format('m/d/Y') }}</td></tr>
    </table>

    <h2>Document</h2>
    <table class="meta-table">
        <tr><td>Title</td><td>{{ $consent->document_title ?? $consent->typeLabel() }}</td></tr>
        <tr><td>Version</td><td>{{ $consent->document_version ?? '-' }}</td></tr>
        <tr><td>Consent type</td><td>{{ $consent->consent_type }}</td></tr>
    </table>

    <h2>Signature</h2>
    <div class="signature-box">
        <img src="{{ $signature }}" alt="signature"/>
    </div>
    <table class="meta-table">
        <tr><td>Signed by</td><td>
            {{ $consent->acknowledged_by }}
            @if (! $consent->signed_by_participant)
                <br><em>Proxy: {{ $consent->proxy_signer_name }} ({{ $consent->proxy_relationship }})</em>
            @endif
        </td></tr>
        <tr><td>Representative type</td><td>{{ $consent->representative_type ?? 'self' }}</td></tr>
        <tr><td>Signed at</td><td>{{ $consent->signed_at?->toDateTimeString() }} UTC</td></tr>
    </table>

    <div class="audit-stamp">
        <strong>Audit stamp -</strong>
        Signed <strong>{{ $consent->signed_at?->toDateTimeString() }} UTC</strong>
        from IP <strong>{{ $consent->signed_ip_address ?? 'unknown' }}</strong>.
        ESIGN/UETA disclaimer version <strong>{{ $consent->esign_disclaimer_version }}</strong>
        was displayed to the signer at capture time.
        Consent record ID: <strong>#{{ $consent->id }}</strong>.
    </div>

    <div class="disclaimer">
        This document was generated by NostosEMR. The electronic signature
        above has the same legal effect as a handwritten signature under the
        federal Electronic Signatures in Global and National Commerce Act
        (ESIGN, 15 U.S.C. §§7001–7031) and the Uniform Electronic Transactions
        Act (UETA) as adopted in this jurisdiction.
    </div>
</body>
</html>
