<?php

// ─── Migration: emr_medications_reference ────────────────────────────────────
// Static reference table for common PACE medications (typeahead + defaults).
//
// Used to pre-populate drug_name, dose, route, frequency dropdowns when a
// clinician adds a new medication. Not a complete drug database — contains
// ~200 medications most commonly prescribed in the PACE population.
//
// Seeded by MedicationsReferenceSeeder (static data, not generated by factories).
// This table is read-only at runtime; no UI for editing it (admin-seeded only).
//
// rxnorm_code enables future FHIR / CDS Hooks integration.
// is_controlled + controlled_schedule drive the witness requirement in eMAR.
// ──────────────────────────────────────────────────────────────────────────────

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('emr_medications_reference', function (Blueprint $table) {
            $table->id();

            // ── Drug identity ─────────────────────────────────────────────────
            $table->string('drug_name', 200)->unique();
            $table->string('rxnorm_code', 20)->nullable()->unique();
            $table->string('drug_class', 100)->nullable();    // e.g., "ACE Inhibitor"
            $table->string('drug_category', 100)->nullable(); // e.g., "Cardiovascular"

            // ── Default dosing (pre-fills the Add Medication form) ────────────
            $table->decimal('common_dose', 8, 3)->nullable();
            $table->string('dose_unit', 20)->nullable();
            $table->string('route', 30)->nullable();
            $table->string('frequency', 20)->nullable();

            // ── Controlled substance flags ─────────────────────────────────────
            $table->boolean('is_controlled')->default(false);
            $table->string('controlled_schedule', 5)->nullable();  // II, III, IV, V

            // ── Search-friendly alias ─────────────────────────────────────────
            $table->string('brand_names', 300)->nullable();  // Comma-separated brand names

            $table->timestamp('created_at')->useCurrent();  // Static reference — no updated_at

            // ── Indexes ───────────────────────────────────────────────────────
            $table->index('drug_class',    'med_ref_class_idx');
            $table->index('drug_category', 'med_ref_category_idx');
            $table->index('drug_name',     'med_ref_name_idx');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('emr_medications_reference');
    }
};
