<?php

// ─── Migration: emr_drug_interaction_alerts ───────────────────────────────────
// Clinical alerts generated by DrugInteractionService when a new medication
// is added to a participant who already has interacting drugs on record.
//
// DrugInteractionService::checkInteractions() is called in MedicationController::store()
// and ::update(). Interactions are matched against emr_drug_interactions_reference.
//
// An alert is not a hard block — it is an informational/warning record that
// must be acknowledged by a clinician to confirm they are aware of the risk.
// Severity 'contraindicated' generates a distinct UI warning (red banner).
//
// Both medication IDs reference emr_medications rows for this participant.
// The drug_name fields are denormalized snapshots for historical accuracy
// (in case medications are later deleted/modified).
// ──────────────────────────────────────────────────────────────────────────────

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('emr_drug_interaction_alerts', function (Blueprint $table) {
            $table->id();

            // ── Scope ─────────────────────────────────────────────────────────
            $table->foreignId('participant_id')
                ->constrained('emr_participants')
                ->cascadeOnDelete();
            $table->foreignId('tenant_id')
                ->constrained('shared_tenants')
                ->cascadeOnDelete();

            // ── Interacting medications ───────────────────────────────────────
            $table->foreignId('medication_id_1')
                ->constrained('emr_medications')
                ->cascadeOnDelete();
            $table->foreignId('medication_id_2')
                ->constrained('emr_medications')
                ->cascadeOnDelete();

            // Denormalized names for historical display even if meds change
            $table->string('drug_name_1', 200);
            $table->string('drug_name_2', 200);

            // ── Interaction details ───────────────────────────────────────────
            $table->enum('severity', [
                'contraindicated',  // Absolute contraindication — strongest warning
                'major',            // Major interaction — significant risk
                'moderate',         // Moderate interaction — monitor closely
                'minor',            // Minor interaction — low clinical significance
            ]);
            $table->text('description');  // Clinical description of the interaction

            // ── Acknowledgement ───────────────────────────────────────────────
            // Unacknowledged alerts appear in the medication alert banner.
            // Acknowledged = clinician reviewed and made an informed decision.
            $table->boolean('is_acknowledged')->default(false);
            $table->foreignId('acknowledged_by_user_id')
                ->nullable()
                ->constrained('shared_users')
                ->nullOnDelete();
            $table->timestamp('acknowledged_at')->nullable();
            $table->text('acknowledgement_note')->nullable();

            $table->timestamp('created_at')->useCurrent();  // Append-only alert log

            // ── Indexes ───────────────────────────────────────────────────────
            $table->index(['participant_id', 'is_acknowledged'], 'drug_alert_participant_ack_idx');
            $table->index(['medication_id_1'],                   'drug_alert_med1_idx');
            $table->index(['medication_id_2'],                   'drug_alert_med2_idx');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('emr_drug_interaction_alerts');
    }
};
