<?php

// ─── Migration: emr_alerts ────────────────────────────────────────────────────
// System-generated and manually created alerts targeting care departments.
//
// Alert lifecycle: created (is_active=true) → acknowledged → resolved (is_active=false)
//
// Triggered by:
//   - ADL threshold breaches (AdlRecordObserver via AlertService)
//   - Assessment overdue (SdrDeadlineEnforcementJob)
//   - Critical allergy flags (AllergyObserver)
//   - SDR escalation (SdrDeadlineEnforcementJob)
//   - Manual creation by clinical staff
//
// target_departments (JSONB): departments that see this alert
//   e.g. ["primary_care", "social_work"]
//
// created_by_system: true = auto-generated by system observer/job
//                    false = created by a user (created_by_user_id will be set)
//
// created_by_user_id: required for HIPAA audit trail on manual alerts (nullable
// so system-generated alerts can set it to null).
// ──────────────────────────────────────────────────────────────────────────────

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('emr_alerts', function (Blueprint $table) {
            $table->id();

            // ── Scope ─────────────────────────────────────────────────────────
            $table->foreignId('tenant_id')
                ->constrained('shared_tenants')
                ->cascadeOnDelete();
            $table->foreignId('participant_id')
                ->nullable()
                ->constrained('emr_participants')
                ->nullOnDelete();

            // ── Classification ────────────────────────────────────────────────
            $table->string('source_module', 50);   // 'adl', 'assessment', 'sdr', 'allergy', 'manual'
            $table->string('alert_type', 100);     // 'adl_decline', 'sdr_overdue', 'assessment_overdue', etc.
            $table->string('title', 255);
            $table->text('message');
            $table->enum('severity', ['info', 'warning', 'critical'])->default('warning');

            // ── Targeting ─────────────────────────────────────────────────────
            // JSONB array of department slugs that should see this alert.
            $table->jsonb('target_departments');

            // ── Origin ────────────────────────────────────────────────────────
            $table->boolean('created_by_system')->default(true);
            $table->foreignId('created_by_user_id')   // null for system-generated
                ->nullable()
                ->constrained('shared_users')
                ->nullOnDelete();

            // ── Acknowledgment ────────────────────────────────────────────────
            $table->foreignId('acknowledged_by_user_id')
                ->nullable()
                ->constrained('shared_users')
                ->nullOnDelete();
            $table->timestamp('acknowledged_at')->nullable();

            // ── Resolution ────────────────────────────────────────────────────
            $table->timestamp('resolved_at')->nullable();
            $table->boolean('is_active')->default(true);

            // ── Append-only: only created_at ──────────────────────────────────
            $table->timestamp('created_at')->useCurrent();

            // ── Indexes ───────────────────────────────────────────────────────
            $table->index(['tenant_id', 'is_active', 'created_at'],   'alerts_tenant_active_idx');
            $table->index(['participant_id', 'alert_type'],            'alerts_participant_type_idx');
            $table->index(['tenant_id', 'acknowledged_at'],            'alerts_tenant_ack_idx');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('emr_alerts');
    }
};
