<?php

// ─── SocialWorkDashboardController ────────────────────────────────────────────
// JSON widget endpoints for the Social Work dashboard.
// All endpoints are tenant-scoped and require the social_work department
// (or super_admin).
//
// Routes (GET, all under /dashboards/social-work/):
//   schedule   : Today's social work / home visit appointments
//   alerts     : Active alerts targeting social_work (incl. HL7 ADT admissions)
//   sdrs       : Open/overdue SDRs assigned to social_work
//   incidents  : Recent open incidents (social work monitors adverse events)
// ─────────────────────────────────────────────────────────────────────────────

namespace App\Http\Controllers\Dashboards;

use App\Http\Controllers\Controller;
use App\Models\Alert;
use App\Models\Appointment;
use App\Models\Incident;
use App\Models\Sdr;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\Auth;

class SocialWorkDashboardController extends Controller
{
    // ── Department guard ──────────────────────────────────────────────────────

    private function requireDept(): void
    {
        $user = Auth::user();
        if (! $user->isSuperAdmin() && $user->department !== 'social_work') {
            abort(403);
        }
    }

    // ── Widget endpoints ──────────────────────────────────────────────────────

    /**
     * Today's social work appointments and home visits.
     */
    public function schedule(): JsonResponse
    {
        $this->requireDept();
        $tenantId = Auth::user()->effectiveTenantId();

        $appointments = Appointment::where('tenant_id', $tenantId)
            ->whereIn('appointment_type', ['social_work', 'home_visit', 'telehealth'])
            ->whereDate('scheduled_start', today())
            ->whereNotIn('status', ['cancelled'])
            ->with(['participant:id,first_name,last_name,mrn', 'provider:id,first_name,last_name'])
            ->orderBy('scheduled_start')
            ->limit(20)
            ->get()
            ->map(fn (Appointment $a) => [
                'id'               => $a->id,
                'participant'      => $a->participant ? [
                    'id'   => $a->participant->id,
                    'name' => $a->participant->first_name . ' ' . $a->participant->last_name,
                    'mrn'  => $a->participant->mrn,
                ] : null,
                'appointment_type' => $a->appointment_type,
                'type_label'       => $a->typeLabel(),
                'scheduled_start'  => $a->scheduled_start?->toTimeString('minute'),
                'scheduled_end'    => $a->scheduled_end?->toTimeString('minute'),
                'status'           => $a->status,
                'href'             => $a->participant
                    ? "/participants/{$a->participant->id}"
                    : '/schedule',
            ]);

        return response()->json(['appointments' => $appointments]);
    }

    /**
     * Active alerts for the social_work department.
     * Includes HL7 ADT admission/discharge alerts generated by ProcessHl7AdtJob.
     */
    public function alerts(): JsonResponse
    {
        $this->requireDept();
        $tenantId = Auth::user()->effectiveTenantId();

        $alerts = Alert::where('tenant_id', $tenantId)
            ->whereJsonContains('target_departments', 'social_work')
            ->where('is_active', true)
            ->with(['participant:id,first_name,last_name'])
            ->orderByRaw("CASE severity WHEN 'critical' THEN 0 WHEN 'warning' THEN 1 ELSE 2 END")
            ->orderBy('created_at', 'desc')
            ->limit(10)
            ->get()
            ->map(fn (Alert $a) => [
                'id'           => $a->id,
                'title'        => $a->title,
                'message'      => $a->message,
                'severity'     => $a->severity,
                'type_label'   => $a->typeLabel(),
                'acknowledged' => $a->isAcknowledged(),
                'participant'  => $a->participant ? [
                    'id'   => $a->participant->id,
                    'name' => $a->participant->first_name . ' ' . $a->participant->last_name,
                ] : null,
                'created_at'   => $a->created_at?->diffForHumans(),
                'href'         => $a->participant
                    ? "/participants/{$a->participant->id}"
                    : '/alerts',
            ]);

        return response()->json(['alerts' => $alerts]);
    }

    /**
     * Open/overdue SDRs assigned to the social_work department.
     */
    public function sdrs(): JsonResponse
    {
        $this->requireDept();
        $tenantId = Auth::user()->effectiveTenantId();

        $sdrs = Sdr::where('tenant_id', $tenantId)
            ->forDepartment('social_work')
            ->open()
            ->with(['participant:id,first_name,last_name'])
            ->orderByRaw('due_at ASC')
            ->limit(15)
            ->get()
            ->map(fn (Sdr $s) => [
                'id'              => $s->id,
                'participant'     => $s->participant ? [
                    'id'   => $s->participant->id,
                    'name' => $s->participant->first_name . ' ' . $s->participant->last_name,
                ] : null,
                'request_type'    => $s->request_type,
                'type_label'      => $s->typeLabel(),
                'priority'        => $s->priority,
                'status'          => $s->status,
                'is_overdue'      => $s->isOverdue(),
                'hours_remaining' => round($s->hoursRemaining(), 1),
                'due_at'          => $s->due_at?->toDateTimeString(),
                'href'            => '/sdrs',
            ]);

        return response()->json([
            'sdrs'          => $sdrs,
            'overdue_count' => Sdr::where('tenant_id', $tenantId)->forDepartment('social_work')->overdue()->count(),
            'open_count'    => Sdr::where('tenant_id', $tenantId)->forDepartment('social_work')->open()->count(),
        ]);
    }

    /**
     * Recent open incidents for social work review.
     * Social workers monitor adverse events for follow-up psychosocial support.
     */
    public function incidents(): JsonResponse
    {
        $this->requireDept();
        $tenantId = Auth::user()->effectiveTenantId();

        $incidents = Incident::forTenant($tenantId)
            ->open()
            ->with(['participant:id,first_name,last_name', 'reportedBy:id,first_name,last_name'])
            ->orderBy('occurred_at', 'desc')
            ->limit(10)
            ->get()
            ->map(fn (Incident $i) => [
                'id'            => $i->id,
                'incident_type' => $i->incident_type,
                'type_label'    => $i->typeLabel(),
                'status'        => $i->status,
                'status_label'  => $i->statusLabel(),
                'rca_required'  => $i->rca_required,
                'occurred_at'   => $i->occurred_at?->toDateString(),
                'participant'   => $i->participant ? [
                    'id'   => $i->participant->id,
                    'name' => $i->participant->first_name . ' ' . $i->participant->last_name,
                ] : null,
                'href'          => '/qa/dashboard',
            ]);

        return response()->json([
            'incidents'   => $incidents,
            'open_count'  => Incident::forTenant($tenantId)->open()->count(),
        ]);
    }
}
