<?php

// ─── Alert Model ──────────────────────────────────────────────────────────────
// System-generated and manually created alerts targeting care departments.
//
// Lifecycle: created (is_active=true) → acknowledged → resolved (is_active=false)
//
// The forUser() scope returns alerts visible to the authenticated user:
//   - tenant_id matches user's tenant
//   - user's department is in target_departments (JSONB array)
//   - is_active = true
//
// created_by_system = true:  auto-generated by observer/job, created_by_user_id = null
// created_by_system = false: manually created, created_by_user_id = the user
// ──────────────────────────────────────────────────────────────────────────────

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Alert extends Model
{
    use HasFactory;

    protected $table = 'emr_alerts';

    // ── Append-only: no updated_at ────────────────────────────────────────────
    public const UPDATED_AT = null;

    // ── Source modules ────────────────────────────────────────────────────────
    public const SOURCE_MODULES = ['adl', 'assessment', 'sdr', 'allergy', 'manual', 'chat'];

    // ── Severity levels ───────────────────────────────────────────────────────
    public const SEVERITIES = ['info', 'warning', 'critical'];

    protected $fillable = [
        'tenant_id',
        'participant_id',
        'source_module',
        'alert_type',
        'title',
        'message',
        'severity',
        'target_departments',
        'metadata',
        'created_by_system',
        'created_by_user_id',
        'acknowledged_by_user_id',
        'acknowledged_at',
        'resolved_at',
        'is_active',
    ];

    protected $casts = [
        'target_departments' => 'array',
        'metadata'           => 'array',
        'created_by_system'  => 'boolean',
        'is_active'          => 'boolean',
        'acknowledged_at'    => 'datetime',
        'resolved_at'        => 'datetime',
    ];

    // ── Relationships ─────────────────────────────────────────────────────────

    public function tenant(): BelongsTo
    {
        return $this->belongsTo(Tenant::class);
    }

    public function participant(): BelongsTo
    {
        return $this->belongsTo(Participant::class);
    }

    public function createdBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by_user_id');
    }

    public function acknowledgedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'acknowledged_by_user_id');
    }

    // ── Scopes ────────────────────────────────────────────────────────────────

    /**
     * Active alerts (is_active = true, not yet resolved).
     */
    public function scopeActive(Builder $query): Builder
    {
        return $query->where('is_active', true);
    }

    /**
     * Unacknowledged alerts (acknowledged_at is null).
     */
    public function scopeUnread(Builder $query): Builder
    {
        return $query->whereNull('acknowledged_at');
    }

    /**
     * Alerts that should appear in the notification bell.
     * Shows: unacknowledged alerts, OR alerts acknowledged within the last 24 hours.
     * Alerts acknowledged more than 24 hours ago are hidden automatically so the
     * bell clears out over time without requiring any user action.
     */
    public function scopeBellVisible(Builder $query): Builder
    {
        return $query->where(function (Builder $q) {
            $q->whereNull('acknowledged_at')
              ->orWhere('acknowledged_at', '>', now()->subHours(24));
        });
    }

    /**
     * Alerts visible to a given user:
     *   - Same tenant
     *   - User's department is in target_departments
     *   - is_active = true
     */
    public function scopeForUser(Builder $query, User $user): Builder
    {
        return $query
            ->where('tenant_id', $user->tenant_id)
            ->whereJsonContains('target_departments', $user->department)
            ->active();
    }

    // ── Business Logic ────────────────────────────────────────────────────────

    /** True if the alert has been acknowledged. */
    public function isAcknowledged(): bool
    {
        return $this->acknowledged_at !== null;
    }

    /** True if the alert has been resolved (inactive). */
    public function isResolved(): bool
    {
        return ! $this->is_active;
    }

    /** Tailwind color classes keyed by UI zone for the severity level. */
    public function severityClasses(): array
    {
        return match ($this->severity) {
            'critical' => ['bg' => 'bg-red-50',   'border' => 'border-red-300',   'text' => 'text-red-700',   'icon' => 'text-red-500'],
            'warning'  => ['bg' => 'bg-amber-50', 'border' => 'border-amber-300', 'text' => 'text-amber-700', 'icon' => 'text-amber-500'],
            default    => ['bg' => 'bg-blue-50',  'border' => 'border-blue-300',  'text' => 'text-blue-700',  'icon' => 'text-blue-500'],
        };
    }

    /** Human-readable type label. */
    public function typeLabel(): string
    {
        return match ($this->alert_type) {
            'adl_decline'        => 'ADL Decline',
            'assessment_overdue' => 'Assessment Overdue',
            'allergy_critical'   => 'Critical Allergy',
            'vital_abnormal'     => 'Abnormal Vital',
            'sdr_warning_24h'    => 'SDR Due in 24h',
            'sdr_warning_8h'     => 'SDR Due in 8h',
            'sdr_overdue'        => 'SDR Overdue',
            'manual'             => 'Manual Alert',
            default              => ucwords(str_replace('_', ' ', $this->alert_type)),
        };
    }
}
