<?php

// ─── DrugInteractionAlert Model ───────────────────────────────────────────────
// Clinical alert for a detected drug-drug interaction.
// Generated by DrugInteractionService::checkInteractions() when a new medication
// is added to a participant's active medication list.
//
// An alert is informational — it does NOT block the medication from being saved.
// A clinician must acknowledge the alert to confirm informed clinical decision.
// Unacknowledged alerts surface in the Medications tab banner and participant header.
//
// Severity levels (from highest to lowest risk):
//   contraindicated — absolute contraindication; strongest warning (red banner)
//   major           — significant risk; should be avoided if possible
//   moderate        — clinically significant; monitor closely
//   minor           — low clinical significance; generally safe to proceed
//
// drug_name_1/2 are denormalized from emr_medications at creation time for
// historical display accuracy (medications can be discontinued/modified later).
//
// Append-only: no updated_at.
// ──────────────────────────────────────────────────────────────────────────────

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class DrugInteractionAlert extends Model
{
    use HasFactory;

    protected $table = 'emr_drug_interaction_alerts';

    // Append-only: updated_at doesn't exist on this table
    public const UPDATED_AT = null;

    public const SEVERITIES = ['contraindicated', 'major', 'moderate', 'minor'];

    protected $fillable = [
        'participant_id',
        'tenant_id',
        'medication_id_1',
        'medication_id_2',
        'drug_name_1',
        'drug_name_2',
        'severity',
        'description',
        'is_acknowledged',
        'acknowledged_by_user_id',
        'acknowledged_at',
        'acknowledgement_note',
    ];

    protected $casts = [
        'is_acknowledged'  => 'boolean',
        'acknowledged_at'  => 'datetime',
        'created_at'       => 'datetime',
    ];

    // ── Relationships ─────────────────────────────────────────────────────────

    public function participant(): BelongsTo
    {
        return $this->belongsTo(Participant::class);
    }

    public function tenant(): BelongsTo
    {
        return $this->belongsTo(Tenant::class);
    }

    public function medication1(): BelongsTo
    {
        return $this->belongsTo(Medication::class, 'medication_id_1');
    }

    public function medication2(): BelongsTo
    {
        return $this->belongsTo(Medication::class, 'medication_id_2');
    }

    /** Clinician who acknowledged this interaction alert. */
    public function acknowledgedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'acknowledged_by_user_id');
    }

    // ── Scopes ────────────────────────────────────────────────────────────────

    public function scopeForTenant(Builder $query, int $tenantId): Builder
    {
        return $query->where('tenant_id', $tenantId);
    }

    /** Alerts not yet reviewed by a clinician. */
    public function scopeUnacknowledged(Builder $query): Builder
    {
        return $query->where('is_acknowledged', false);
    }

    /** Critical alerts requiring urgent clinician review (contraindicated or major). */
    public function scopeHighSeverity(Builder $query): Builder
    {
        return $query->whereIn('severity', ['contraindicated', 'major']);
    }

    // ── Business Logic ────────────────────────────────────────────────────────

    /** Acknowledge this alert, recording who reviewed it and why they accepted the risk. */
    public function acknowledge(User $user, ?string $note = null): void
    {
        $this->update([
            'is_acknowledged'         => true,
            'acknowledged_by_user_id' => $user->id,
            'acknowledged_at'         => now(),
            'acknowledgement_note'    => $note,
        ]);
    }

    /** True if this interaction warrants a persistent red banner (not just a warning). */
    public function isContraindicated(): bool
    {
        return $this->severity === 'contraindicated';
    }

    /** UI color class corresponding to severity level. */
    public function severityColor(): string
    {
        return match($this->severity) {
            'contraindicated' => 'red',
            'major'           => 'orange',
            'moderate'        => 'amber',
            'minor'           => 'yellow',
            default           => 'gray',
        };
    }
}
